- .eslintrc
- .prettierrc
- .vscode/settings.json
- package-lock.json
- package.json
- src/App.js
1. prettier 설정
2. eslint 설정
3. styled-components 설정
4. db 폴더 추가
---
1. develop 브랜치 추가
> feature: eslint, styled-components, prettier 추가

- .eslintrc
- .gitignore
- .prettierrc
- package-lock.json
- package.json
- src/App.js
1. eslint 추가
2. prettier 추가
3. gitignore 수정
- vscode
```
{
"editor.formatOnSave": true,
"[javascript]": {
"editor.formatOnSave": true,
"editor.defaultFormatter": "esbenp.prettier-vscode"
},
"eslint.alwaysShowStatus": true,
"files.autoSave": "onFocusChange",
"editor.codeActionsOnSave": {
"source.fixAll.eslint": true
}
}
```
> eslint, prettier 추가, gitignore 수정

- src/pages/management/MngCertify.jsx
- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/pages/management/MngValue.jsx
- src/pages/management/Mngtrade.jsx
1. pages 폴더에 management 폴더 추가
2. MngConsulting, MngCertify, MngCredit, MngTrade, MngValue 파일 추가
> pages폴더에 management 폴더 및 파일 추가

- src/pages/ir/IrPerfo.jsx
- src/pages/ir/IrPlan.jsx
- src/pages/ir/IrProcess.jsx
- src/pages/ir/index.jsx
1. pages 폴더에 ir 폴더 추가
2. index, IrPerfo, IrPlan, IrProcess 파일 추가
> feature:ir 페이지 구성

- src/pages/zeta/ZetaCi.jsx
- src/pages/zeta/ZetaConsul.jsx
- src/pages/zeta/ZetaHistory.jsx
- src/pages/zeta/ZetaMap.jsx
- src/pages/zeta/ZetaNetwork.jsx
- src/pages/zeta/ZetaPeople.jsx
- src/pages/zeta/index.jsx
1. pages 폴더에 zeta 폴더 추가
2. index, ZetaHistory, ZetaCi, ZetaConsul, ZetaPeople, ZetaNetwork, ZetaMap 파일 추가
> feature:zeta 페이지 구성'

- src/pages/global/GbCase.jsx
- src/pages/global/GbStategy.jsx
1. pages 폴더에 global 폴더 생성
2. index, GbStategy, GbCase 파일 추가
> feature:global 페이지 구성

- src/pages/zeta/ZetaCi.jsx
- src/pages/zeta/ZetaConsul.jsx
- src/pages/zeta/ZetaHistory.jsx
- src/pages/zeta/ZetaMap.jsx
- src/pages/zeta/ZetaNetwork.jsx
- src/pages/zeta/ZetaPeople.jsx
- src/pages/zeta/index.jsx
1. zeta 폴더에 있는 파일 tab width 간격 변경(4 -> 2)
> misc: tab width 간격 변경

- src/pages/maipo/MaipoInfo.jsx
- src/pages/maipo/MaipoPerfo.jsx
- src/pages/maipo/MaipoPro.jsx
> misc : M&A/IPO tab width 변경

- src/pages/notice/Column.jsx
- src/pages/notice/News.jsx
- src/pages/notice/Qna.jsx
1. pages에 notice 폴더 추가
2. News, Column, Qna 파일 추가
> feature: notice 페이지 구성

- src/components/common/Header/Sitemap.jsx
1. docs: header 의 Sitemap 부분 마크업 수정
> docs: header 의 Sitemap 부분 마크업 수정

- src/pages/landing/index.jsx
1. src 폴더에 landing 폴더 생성 및 index 파일 생성
> feature:landing 랜딩 파일 생성

- src/App.js
- src/components/common/Header/Gnb.jsx
- src/components/common/Header/index.jsx
- src/styles/header/Header.scss
1. app.js 에 header 추가
2. header style 추가
> feature : header style 추가

- src/components/common/Header/Gnb.jsx
- src/components/common/Header/Sitemap.jsx
- src/components/common/Header/Util.jsx
1. header 에 gnb, sitemap, util 컴포넌트에 a 태그를 link 태그로 수정
> feature: a -> Link 태그로 수정

- src/App.js
- src/components/common/SubBanner/index.jsx
- src/pages/ir/Accordion.jsx
- src/pages/ir/IrPerfo.jsx
- src/pages/ir/IrPlan.jsx
- src/pages/ir/IrProcess.jsx
- src/pages/ir/index.jsx
- src/pages/landing/index.jsx
- src/styles/GlobalStyle.scss
- src/styles/ir/Accordion.scss
1. ir SubBanner 추가
2. SubBanner 컴포넌트 width, line-height 값 수정
> feature:ir SubBanner 추가 및 SubBanner 컴포넌트 속성 수정

- src/components/common/Header/Gnb.jsx
- src/styles/header/Header.scss
> feature: header style 수정

- src/components/common/Header/Sitemap.jsx
- src/components/common/Header/Util.jsx
- src/components/common/Header/index.jsx
- src/styles/header/Header.scss
1. header sitemap 버튼 기능 추가 : 클릭하면 sitemap 창이 나오도록 설정
> feature: header sitemap 버튼 기능 추가

- src/App.js
- src/pages/maipo/MaipoInfo.jsx
- src/styles/header/Header.scss
1. header 에 hover 하면 배경색 변경
2. header 에 hover 하면 안의 요소 색 변경
> feature: header 배경색 변경

- src/App.js
- src/components/Notice/QnaTable.jsx
- src/components/Notice/QnaTableList.jsx
- src/pages/notice/Qna.jsx
- src/styles/qna/qna.scss
- src/styles/qna/qnaTable.scss
1. QnA 페이지 마크업
2. QnA Table, TableList 컴포넌트 작업
3. 스타일 적용
1. json 데이터 reverse 안되는 부분 수정할 것
2. 페이지네이션 추가해야 됨
3. comment 있을 경우에만 isAnswerBtn으로 되도록 변경(comment 없을 시 answerBtn으로 되도록)
4. 리스트 클릭할 때, 세부 페이지 보이도록 추가해야 됨
5. 스타일 디테일한 부분 수정해야 됨(돋보기 이미지 추가, 제목 부분에 간격)
> feature: QnA 페이지 및 컴포넌트 작업, 스타일 적용

- src/db/network.json
> feature:main network.json 오류 수정

- src/App.js
- src/components/Notice/InfoList.jsx
- src/db/m&a-investList.json
- src/pages/notice/DataInfoItem.jsx
- src/styles/notice/dataInfo.scss
1. DataInfo 작업HTML, SCSS)
2. m&a json 파일 createdAt 추가
> feature: DataInfo 작업 및 m&a json 파일 createdAt 추가

- src/pages/notice/DataInfo.jsx
1. DataInfo 페이지 작업
1. DataInfo 컴포넌트 디테일 작업
2. 더보기 버튼 클릭시 3개씩 나오게끔 작업
3. 데이터 연결 작업
> feature: DataInfo 페이지 작업

- src/pages/global/GbAccordion.jsx
- src/pages/global/GbCase.jsx
- src/pages/global/GbStrategy.jsx
- src/pages/global/index.jsx
- src/pages/ir/Accordion.jsx
- src/styles/global/gbAccordion.scss
- src/styles/global/gbCase.scss
- src/styles/global/gbStrategy.scss
- src/styles/global/index.scss
> feature/global 스타일링 수정

- src/components/Notice/InfoList.jsx
- src/pages/notice/DataInfo.jsx
- src/styles/notice/dataInfo.scss
> feature:dataInfo 마크업 및 스타일 완료

- src/App.js
- src/components/Notice/NewsList.jsx
- src/pages/notice/News.jsx
- src/styles/notice/news.scss
1. news 페이지 마크업 및 스타일 초기 작업 완료
1. 아직 초기 작업 상태라 수정해야 될 부분 많음
2. 이미지 교체 및 json 데이터 불러와야 됨
3. newsList 컴포넌트 생성해야 됨
> feature: news 페이지 마크업 및 스타일 초기작업

- src/App.js
- src/components/common/Header/Gnb.jsx
- src/components/common/SubBanner/index.jsx
- src/pages/maipo/MaipoInfo.jsx
- src/pages/maipo/tab/IpoInfo.jsx
- src/pages/maipo/tab/IpoPerfo.jsx
- src/pages/maipo/tab/IpoPro.jsx
- src/pages/maipo/tab/MaInfo.jsx
- src/pages/maipo/tab/MaPerfo.jsx
- src/pages/maipo/tab/MaPro.jsx
- src/styles/maipo/MaIpo.scss
1. maipo 개요와 탭 부분 작업 완료
1. jsx
2. style
> feature: maipo 탭 작업

- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPerfo.jsx
- src/pages/maipo/MaIpoPro.jsx
1. Maipo 파일명에서 MaIpo로 파일명 수정하였음(혜인님 대신 수정함)
> misc: Maipo에서 MaIpo로 파일명 수정(혜인님 대신 수정함)

- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPerfo.jsx
- src/pages/maipo/MaIpoPro.jsx
> feature: 파일 삭제 후 추가

- package-lock.json
- package.json
- src/pages/index.jsx
- src/pages/main/OurBusiness.jsx
- src/pages/main/Performance.jsx
- src/pages/main/ZetaIntroduction.jsx
- src/styles/main/OurBusiness.scss
- src/styles/main/Performance.scss
- src/styles/main/ZetaIntrduction.scss
1. 메인 our business 마크업 및 스타일링
2. 메인 performance 마크업 및 스타일링
> feature;mainBus 메인영역 마크업 및 스타일링

- src/App.js
- src/pages/landing/index.jsx
> feature:consulting 첫페이지로 랜딩 수정 및 컨설팅 연결

- src/App.js
- src/components/common/Header/Gnb.jsx
- src/components/common/Header/Sitemap.jsx
- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPerfo.jsx
- src/pages/maipo/MaIpoPro.jsx
- src/styles/header/Header.scss
- src/styles/maipo/MaIpoInfo.scss
- src/styles/maipo/MaIpoPerfo.scss
- src/styles/maipo/MaIpoPro.scss
1. maipo 탭 클릭 스타일 고정 수정
2. header style 수정
> feature: maipo 탭 수정, header 수정

- src/components/common/TopBtn/index.jsx
> feature:consul top 수정

- src/styles/GlobalStyle.scss
> feature inner 값 수정

- src/App.js
- src/components/main/InfoSwiper.jsx
- src/components/main/InfoSwiperItem.jsx
- src/components/main/InformationList.jsx
- src/pages/index.jsx
- src/styles/main/information.scss
1. main에 information 부분 스와이퍼 적용
2. swiper 스타일 적용
1. 데이터 중복으로 들어오는 부분 수정 예정
2. 페이지네이션 불렛 위치 조정 수정 예정
> feature: main information 부분 스와이퍼 작업 및 스타일 적용

- src/App.js
- src/components/main/InfoSwiper.jsx
- src/pages/notice/DataInfo.jsx
- src/pages/notice/DetailInfoItem.jsx
- src/pages/notice/News.jsx
- src/pages/notice/NewsDetailItem.jsx
- src/pages/notice/Qna.jsx
- src/pages/notice/QnaDetail.jsx
- src/styles/main/information.scss
- src/styles/notice/news.scss
- src/styles/notice/newsDetail.scss
- src/styles/notice/newsItem.scss
- src/styles/qna/qnaDetail.scss
- src/styles/qna/qnaTable.scss
1. 소식, 자료 페이지 나뉘어져 있는 탭 navigation 연결
2. 수정한 부분
- qna 각 행에 cursor pointer
- qna 상세페이지 글씨 작은 부분
- 상세페이지 글씨 1.8rem으로 설정
- 소식 페이지 line-height 1.7로 설정
- 소식 페이지에 스와이퍼 타이틀 word-break keep-all로 설정
> feature: 각 탭 navigate 연결 및 스타일 수정

- src/pages/notice/NewsDetailItem.jsx
1. NewsDetailItem.jsx 파일 오류 수정
> feature: NewsDetailItem.jsx 파일 오류 수정

- src/components/Notice/QnaTableList.jsx
- src/components/main/InfoSwiper.jsx
- src/components/main/InformationList.jsx
- src/pages/index.jsx
- src/pages/login/index.jsx
- src/pages/notice/DataInfo.jsx
- src/pages/notice/Qna.jsx
- src/pages/notice/QnaDetail.jsx
- src/styles/login/login.scss
- src/styles/main/information.scss
- src/styles/notice/dataInfo.scss
- src/styles/notice/detailInfoItem.scss
- src/styles/notice/news.scss
- src/styles/notice/newsDetail.scss
- src/styles/qna/qna.scss
- src/styles/qna/qnaDetail.scss
- src/styles/qna/qnaTable.scss
1. 각 페이지 탭 부분 cursor: pointer
2. 더 보기 버튼 위치 수정
3. 상세페이지 이미지 센터로 수정
4. 뉴스&칼럼 기사 타이틀 및 내용 line-height: 1.7로 수정
> feature: Q&A 페이지, 자료 페이지, 소식 페이지, Main에 Information 수정사항 반영

- src/pages/global/GbCase.jsx
- src/pages/global/GbStrategy.jsx
- src/pages/global/index.jsx
- src/pages/main/Performance.jsx
- src/pages/main/ZetaIntroduction.jsx
- src/styles/global/gbCase.scss
- src/styles/global/gbStrategy.scss
- src/styles/global/index.scss
- src/styles/main/OurBusiness.scss
- src/styles/main/Performance.scss
- src/styles/main/ZetaIntrduction.scss
1. feature/global 반응형 작업
2. main 반응형 작업
> feature/global 반응형 작업

- src/pages/global/index.jsx
- src/pages/main/Performance.jsx
- src/styles/global/index.scss
- src/styles/main/ZetaIntrduction.scss
> feature/global 반응형 작업 수정 완료

- src/pages/landing/index.jsx
> feature:ld test2

- src/App.js
- src/components/common/Header/Gnb.jsx
- src/components/common/Header/Search.jsx
- src/components/common/Header/Sitemap.jsx
- src/components/common/Header/Util.jsx
- src/styles/header/Header.scss
- src/styles/maipo/MaIpoAccordion.scss
- src/styles/maipo/MaIpoInfo.scss
> feature: header 반응형 구현 완료

- src/components/Notice/NewsSwiper.jsx
- src/db/govSupportList.json
- src/db/technologyList.json
- src/pages/notice/Qna.jsx
- src/styles/main/information.scss
- src/styles/notice/dataInfo.scss
- src/styles/notice/detailInfoItem.scss
- src/styles/notice/news.scss
- src/styles/notice/newsDetail.scss
- src/styles/notice/newsItem.scss
- src/styles/qna/qna.scss
1. Main Information 반응형 작업
2. json 파일 일부 수정
3. Q&A 페이지 select 부분 화살표 수정
4. 뉴스 페이지 반응형 작업
1. 아직 반응형 작업 완료 상태 아님
> feature: 반응형 작업 및 json 파일 일부 수정

- src/components/common/Footer/index.jsx
- src/db/serviceField.json
- src/index.js
- src/pages/zeta/ZetaCi.jsx
- src/pages/zeta/ZetaHistory.jsx
- src/pages/zeta/ZetaMap.jsx
- src/pages/zeta/ZetaNetwork.jsx
- src/pages/zeta/index.jsx
- src/styles/footer/footer.scss
- src/styles/zeta/index.scss
- src/styles/zeta/zetaCi.scss
- src/styles/zeta/zetaConsul.scss
- src/styles/zeta/zetaHistory.scss
- src/styles/zeta/zetaMap.scss
- src/styles/zeta/zetaNetwork.scss
> zeta반응형 작업완료

- src/styles/consul/consultingPage.scss
- src/styles/consul/index.scss
- src/styles/main/Partners.scss
- src/styles/zeta/zetaPeople.scss
> feature:consul 모달창 반응형 완료

- src/App.js
- src/pages/main/NewsColumn.jsx
- src/styles/footer/footer.scss
> feature:라우팅 오류 해결

- src/App.js
- src/pages/lang/LangAcco.jsx
- src/pages/lang/LangEng.jsx
- src/styles/lang/LangEng.scss
- src/styles/main/Performance.scss
1. 반응형 마크업 수정
2. eng 페이지 마크업 및 스타일링
> feature/gb 반응형 수정 및 lang Eng 마크업, 스타일링

- src/pages/main/ZetaIntroduction.jsx
- src/styles/global/gbCase.scss
- src/styles/global/gbStrategy.scss
- src/styles/global/index.scss
- src/styles/main/OurBusiness.scss
- src/styles/main/Performance.scss
1. 메인 영역 반응형 수정
2. 서브페이지 반응형 수정
> feature/global 메인, 서브페이지 반응형 작업 수정

- src/App.js
- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/pages/management/MngValue.jsx
- src/styles/mng/mngCertify.scss
- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngCredit.scss
- src/styles/mng/mngTrade.scss
- src/styles/mng/mngValue.scss
> feature manage 반응형 수정

- src/components/common/Header/Gnb.jsx
- src/components/common/Header/Search.jsx
- src/components/common/Header/Sitemap.jsx
- src/components/common/Header/Util.jsx
- src/pages/maipo/tab/MaInfo.jsx
- src/styles/header/Header.scss
- src/styles/maipo/MaIpoAccordion.scss
- src/styles/maipo/MaIpoInfo.scss
- src/styles/maipo/MaIpoPro.scss
1. header 반응형 수정
2. maipo 반응형 수정
> feature: header, maipo 반응형 수정

- src/App.js
- src/components/common/Header/Gnb.jsx
- src/pages/management/MngCertify.jsx
- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/pages/management/MngValue.jsx
- src/pages/management/Mngtrade.jsx
- src/styles/mng/mngValue.scss
> mng page 3depth 브레드크럼 추가

- src/App.js
- src/components/common/Header/Gnb.jsx
- src/components/common/Header/Sitemap.jsx
- src/components/common/Header/Util.jsx
- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPerfo.jsx
- src/pages/maipo/MaIpoPro.jsx
> feature: maipo 브레드크럼 구현

- src/pages/global/GbCase.jsx
- src/pages/global/GbStrategy.jsx
- src/pages/global/index.jsx
- src/styles/global/gbCase.scss
- src/styles/global/gbStrategy.scss
- src/styles/global/index.scss
- src/styles/main/Performance.scss
1. 메인페이지 반응형 수정
2. 서브페이지 반응형 수정
> feature/global 반응형 수정

- public/index.html
- src/components/common/SubBanner/BreadCrumb.jsx
- src/pages/zeta/ZetaCi.jsx
- src/styles/zeta/index.scss
- src/styles/zeta/zetaCi.scss
1.index.scss 작업 추가
2.브레드크럼 반응형 작업 변경
3.ci.jsx변경 
4.ci.scss변경
> index.scss 작업 추가, 브레드크럼 반응형 작업 변경, ci.jsx변경 ,ci.scss변경

- src/pages/main/Performance.jsx
- src/styles/main/Performance.scss
> 메인영역 반응형 수정

- src/components/common/Header/Search.jsx
- src/components/common/Header/Util.jsx
- src/components/common/Header/index.jsx
- src/styles/header/Header.scss
1. header 언어, 검색 파트에 기능, 스타일링, 반응형 완료
> feature: header 기능, 반응형 모두 완료

- src/components/common/Header/Gnb.jsx
- src/components/common/Header/Search.jsx
- src/components/common/Header/Util.jsx
- src/components/common/Header/index.jsx
- src/pages/maipo/tab/IpoInfo.jsx
- src/pages/maipo/tab/MaInfo.jsx
- src/styles/header/Header.scss
- src/styles/maipo/MaIpoAccordion.scss
- src/styles/maipo/MaIpoPro.scss
1. header 세부 수정 완료
- 언어 chn 페이지 링크 추가
- 언어 페이지 클릭하면 넘어가면서 언어 선택 파트 꺼지기
- 검색창에 버튼들 누르면 해당 페이지 넘어가면서 검색창 꺼지기
2. maipo 세부 수정 완료
- maipo 개요 파란색 글자 타이핑
- maipo 프로세스 아코디언 높이 수정
> feature: header, maipo 세부 수정 완료

- src/App.js
- src/pages/login/index.jsx
- src/styles/login/login.scss
- src/styles/notice/dataInfo.scss
1. 로그인 페이지 반응형 및 css 수정
2. 로그인 페이지 기능 수정
> feature: login 페이지 반응형 및 수정

- src/pages/management/MngCertify.jsx
- src/pages/management/MngValue.jsx
- src/styles/GlobalStyle.scss
- src/styles/mng/mngConsulting.scss
> feature theme 위치 수정

- src/pages/management/MngCertify.jsx
- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/pages/management/MngValue.jsx
- src/pages/management/Mngtrade.jsx
- src/styles/GlobalStyle.scss
- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngValue.scss
> dark mode scss 수정

- src/pages/notice/DataInfo.jsx
- src/pages/notice/News.jsx
- src/pages/notice/Qna.jsx
- src/pages/notice/QnaDetail.jsx
- src/styles/main/information.scss
- src/styles/notice/dataInfo.scss
- src/styles/notice/detailInfoItem.scss
- src/styles/notice/news.scss
- src/styles/notice/newsDetail.scss
- src/styles/notice/newsItem.scss
- src/styles/qna/qna.scss
- src/styles/qna/qnaDetail.scss
- src/styles/qna/qnaTable.scss
1. Q&A 페이지 검색 기능 추가
2. 자료 페이지 검색 기능 추가
3. scss 주석 처리된 부분 삭제함
1. 자료 페이지 검색시 총 갯수 및 더보기 눌렀을 때 없으면 안 나오게 수정해야 됨
2. 뉴스 페이지 검색 기능 추가해야 됨
> feature: qna, 자료 페이지 검색 기능 추가

- src/components/common/Header/Sitemap.jsx
- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPerfo.jsx
- src/pages/maipo/MaIpoPro.jsx
- src/pages/maipo/tab/IpoInfo.jsx
- src/pages/maipo/tab/IpoPerfo.jsx
- src/pages/maipo/tab/MaInfo.jsx
- src/pages/maipo/tab/MaPerfo.jsx
- src/styles/maipo/MaIpoInfo.scss
- src/styles/maipo/MaIpoPerfo.scss
- src/styles/maipo/MaIpoPro.scss
> feature: maipo 나이트 모드 구현 완료

- src/pages/global/GbCase.jsx
- src/pages/global/GbStrategy.jsx
- src/pages/global/index.jsx
- src/styles/global/gbCase.scss
- src/styles/global/gbStrategy.scss
- src/styles/global/index.scss
> feature/global 다크모드 수정

- src/pages/zeta/ZetaConsul.jsx
- src/pages/zeta/ZetaHistory.jsx
- src/styles/zeta/zetaConsul.scss
- src/styles/zeta/zetaHistory.scss
1.컨설팅부문jsx,sass 다크모드 추가
2.연혁jsx,sass 다크모드 추가
3.연혁 헤더스타일 추가
> 컨설팅부문jsx,sass, 연혁jsx,sass 다크모드 추가, 연혁 헤더스타일 추가

- src/pages/management/MngCertify.jsx
- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/pages/management/MngValue.jsx
- src/pages/management/Mngtrade.jsx
- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngCredit.scss
- src/styles/mng/mngValue.scss
> mngcircle scss 수정

- src/pages/notice/DataInfo.jsx
- src/pages/notice/News.jsx
- src/styles/notice/dataInfo.scss
- src/styles/notice/news.scss
- src/styles/notice/newsItem.scss
1. 자료 페이지 검색 기능 및 스타일 수정
2. 뉴스 페이지 검색 기능 및 스타일 수정
> 자료, 뉴스 페이지 검색 기능 및 스타일 수정

- src/pages/notice/Qna.jsx
- src/pages/notice/QnaDetail.jsx
- src/pages/notice/QnaWrite.jsx
> qna 페이지  오류 수정

- src/pages/notice/QnaDetail.jsx
> qna detail 오류 수정

- src/pages/global/GbCase.jsx
> react.memo 추가

- src/styles/global/gbCase.scss
> 다크모드 지도 추가

- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/styles/mng/mngCertify.scss
- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngTrade.scss
- src/styles/mng/mngValue.scss
> mngcredit 메모이제이션 적용

- src/pages/zeta/ZetaConsul.jsx
- src/pages/zeta/ZetaHistory.jsx
- src/pages/zeta/ZetaMap.jsx
- src/pages/zeta/index.jsx
> map사용 React.memo추가

- src/pages/global/GbStategy.jsx
> 불필요한 파일 삭제

- src/pages/notice/Qna.jsx
1. Q&A select onChange state 초기값 수정
> qna select state 초기값 수정

- src/pages/notice/QnaDetail.jsx
- src/styles/notice/news.scss
1. Q&A detail 페이지 브레드크럼 추가
2. 뉴스리스트 375 모바일 스타일 수정
> qna detail 페이지 브레드크럼 추가 및 뉴스리스트 스타일 수정

- src/App.js
- src/pages/ir/IrProcess.jsx
- src/pages/landing/index.jsx
- src/pages/main/MainAll.jsx
- src/pages/main/MainColumn.jsx
- src/pages/main/MainNews.jsx
- src/pages/main/NewsColumn.jsx
- src/pages/main/Partners.jsx
- src/pages/notice/Qna.jsx
- src/pages/notice/QnaDetail.jsx
- src/pages/notice/QnaWrite.jsx
- src/pages/zeta/ZetaPeople.jsx
- src/styles/qna/qna.scss
- src/styles/qna/qnaDetail.scss
> feature:write crud 완성

- src/pages/landing/index.jsx
- src/styles/qna/qnaWrite.scss
1. qna write 입력 행간 수정
2. 랜딩 페이지 수정
> feature:write 입력 행간 수정 및 랜딩페이지 수정

- src/components/common/SubBanner/index.jsx
> subBanner 1차 수정

- src/components/common/SubBanner/index.jsx
- src/pages/notice/Qna.jsx
1.  dangerouslySetInnerHTML 제외함
2. 타이틀에 개행문자 넣어줌
3. 미디어쿼리 적용 all로 변경함
> subBanner 2차 수정

- src/components/common/SubBanner/index.jsx
> subBanner 수정

- src/components/common/SubBanner/index.jsx
1. 서브배너 3차 수정
p를 스타일드 컴포넌트로 변경
> feature:subbanner 3차 수정

- src/components/common/Consulting/ConsultingPage.jsx
- src/components/common/SubBanner/index.jsx
- src/pages/global/GbStrategy.jsx
- src/pages/ir/IrPlan.jsx
- src/pages/ir/IrProcess.jsx
- src/pages/ir/index.jsx
- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPro.jsx
- src/pages/management/MngCertify.jsx
- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/pages/management/MngValue.jsx
- src/pages/management/Mngtrade.jsx
- src/pages/notice/DataInfo.jsx
- src/pages/notice/DetailInfoItem.jsx
- src/pages/notice/News.jsx
- src/pages/notice/NewsDetailItem.jsx
- src/pages/notice/QnaDetail.jsx
- src/pages/notice/QnaWrite.jsx
- src/pages/zeta/ZetaCi.jsx
- src/pages/zeta/ZetaMap.jsx
- src/pages/zeta/ZetaNetwork.jsx
- src/pages/zeta/index.jsx
1. subBanner 최종 수정
2. 각 페이지 타이틀 개행문자 추가하였음
> subBanner 최종 수정 및 각 페이지 타이틀 개행문자 추가

- src/App.js
- src/pages/zeta/ZetaHistory.jsx
- src/styles/GlobalStyle.scss
- src/styles/footer/footer.scss
- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngValue.scss
- src/styles/zeta/index.scss
- src/styles/zeta/zetaHistory.scss
1.app.js 랜더링관련수정
2.globalStyle 수정
3.다크모드 관련 스타일 수정 -mng, global
4.zeta 스타일 수정
> globalStyle 및 app.js 랜더링관련수정

- src/pages/maipo/MaIpoPerfo.jsx
1. m&a ipo subBanner에 들어가는 title 개행문자 수정
> subBanner에 들어가는 title 개행문자로 수정

- src/pages/main/OurBusiness.jsx
- src/styles/main/OurBusiness.scss
> our business 동영상 재생 수정

- public/index.html
- src/styles/ResetStyle.js
1. resetStyle 추가 
2. index.html 설정 추가
> resetStyle 추가 및 index.html 설정 추가

- src/styles/footer/footer.scss
- src/styles/zeta/zetaCi.scss
- src/styles/zeta/zetaConsul.scss
- src/styles/zeta/zetaMap.scss
1. footer반응형 변경
2.  zetaCi반응형 변경
3. zetaConsul반응형 변경
4. zetaMap반응형 변경
> feature: footer, zetaCi,zetaConsul,zetaMap반응형 변경

- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPro.jsx
- src/styles/maipo/MaIpoInfo.scss
- src/styles/maipo/MaIpoPro.scss
> feature: maipo 반응형 수정

- src/styles/main/OurBusiness.scss
> our business 반응형 수정

- src/styles/main/ZetaIntrduction.scss
> zeta introduction 반응형 수정

- src/styles/main/ZetaIntrduction.scss
> zeta introduction content 수정

- src/styles/main/ZetaIntrduction.scss
> introduction content 수정

- src/components/common/Darkmode/ModeChange.jsx
- src/components/common/Darkmode/PageBase.jsx
- src/components/common/Darkmode/ThemeContext.jsx
- src/pages/global/index.jsx
- src/pages/ir/index.jsx
- src/pages/management/MngCertify.jsx
- src/pages/management/MngConsulting.jsx
- src/pages/management/MngCredit.jsx
- src/pages/management/MngValue.jsx
- src/pages/management/Mngtrade.jsx
- src/styles/GlobalStyle.css
- src/styles/GlobalStyle.css.map
- src/styles/GlobalStyle.scss
- src/styles/global/gbCase.scss
- src/styles/global/gbStrategy.scss
- src/styles/global/index.scss
- src/styles/ir/index.scss
- src/styles/maipo/MaIpoInfo.scss
- src/styles/maipo/MaIpoPerfo.scss
- src/styles/mng/mngCertify.scss
- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngCredit.scss
- src/styles/mng/mngTrade.scss
- src/styles/mng/mngValue.scss
- src/styles/notice/news.scss
- src/styles/zeta/zetaHistory.scss
feature dark mode component 추가 및 mng 페이지 반응형 수정
> feature dark mode component 추가

- src/styles/maipo/MaIpoInfo.scss
> feature:maIpo info.scss 컴플릭 수정

- src/pages/zeta/ZetaConsul.jsx
- src/pages/zeta/ZetaHistory.jsx
- src/styles/zeta/zetaHistory.scss
1.zetaConsul 다크모드 컴포넌트 변경
2.zetaHistory 다크모드 컴포넌트 변경
> feature:zetaConsul, zetaHistory다크모드 컴포넌트 변경

- src/components/common/Consulting/ConsultingPage.jsx
- src/styles/consul/index.scss
- src/styles/landing/index.scss
> Feature/consulting breadcrumbs 연결

- src/pages/global/GbCase.jsx
- src/pages/global/GbStrategy.jsx
- src/pages/global/index.jsx
- src/styles/global/gbCase.scss
- src/styles/global/gbStrategy.scss
- src/styles/global/index.scss
> 서브페이지 다크모드 수정

- src/pages/login/index.jsx
- src/pages/notice/DataInfo.jsx
- src/pages/notice/DetailInfoItem.jsx
- src/pages/notice/News.jsx
- src/pages/notice/NewsDetailItem.jsx
- src/pages/notice/Qna.jsx
- src/pages/notice/QnaDetail.jsx
- src/styles/login/login.scss
- src/styles/notice/news.scss
1. 소식 자료 페이지 dark mode 추가
2. 로그인 기능 수정
- 로컬스토리지에 로그인 정보 추가해놓음
- 로컬스토리지에 로그인 정보와 일치할 경우 로그인 되게끔 구현
- 버튼 클릭 외에도 로그인시 엔터를 쳐서 로그인 가능하게 onKeyDown 이벤트 추가해놓음
> feature: 소식 자료 페이지 dark mode 추가 및 Login 기능 수정

- src/styles/zeta/zetaHistory.scss
> feature:zetaHistory.scss다크모드 수정

- src/pages/maipo/MaIpoInfo.jsx
- src/pages/maipo/MaIpoPerfo.jsx
- src/pages/maipo/MaIpoPro.jsx
- src/styles/maipo/MaIpoInfo.scss
- src/styles/maipo/MaIpoPerfo.scss
> feature: maipo 오류 수정

- src/pages/notice/QnaDetail.jsx
- src/styles/notice/dataInfo.scss
- src/styles/notice/news.scss
- src/styles/notice/newsItem.scss
- src/styles/qna/qna.scss
- src/styles/qna/qnaDetail.scss
- src/styles/qna/qnaTable.scss
1. 소식 자료 페이지 dark mode시 글씨 수정
2. Q&A 게시판 safari에 맞게 수정
> 소식 자료 페이지 dark mode시 글씨 수정 및 qna 게시판 safari에 맞게 수정

- src/components/common/Consulting/ConsulModal.jsx
- src/components/common/Consulting/ConsultingPage.jsx
- src/styles/consul/index.scss
1. consulting form 안에 form 중첩 수정
2. for ->htmlFor로 수정
3. enctype -> encType으로 수정
> consulting form 수정

- src/styles/consul/index.scss
> consulting style 파일 주석 지움

- src/styles/header/Header.scss
> feature: 헤더 언어 부분 반응형 수정

- src/styles/notice/dataInfo.scss
- src/styles/notice/news.scss
- src/styles/qna/qna.scss
1. news 검색창 부분 dark mode 수정
2. datainfo 검색창 및 더보기 버튼 dark mode 수정
3. qna select tag pointer 추가
> news, datainfo dark mode시 수정 안된 부분 수정

- src/styles/notice/dataInfo.scss
- src/styles/notice/news.scss
> 소식 자료 페이지 style 수정

- src/styles/mng/mngValue.scss
> mngValue style 수정

- src/styles/header/Header.scss
> feature: header 반응형 수정

- src/pages/management/MngConsulting.jsx
- src/styles/mng/mngConsulting.scss
> mngConsulting 페이지 style 수정

- src/styles/zeta/zetaHistory.scss
> zetaHistory 다크모드수정

- src/styles/notice/dataInfo.scss
- src/styles/notice/news.scss
> dark button과 title 간격 수정

- src/styles/maipo/MaIpoInfo.scss
> feature: maipo 이미지 크기 수정

- src/App.js
> feature:main lazy routes 로딩 스타일 추가

- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngTrade.scss
> mng페이지 style 수정

- src/styles/consul/consultingPage.scss
> feature:consul 오류 수정

- src/pages/main/MainColumn.jsx
- src/pages/main/MainNews.jsx
- src/pages/main/NewsColumn.jsx
- src/pages/notice/News.jsx
- src/pages/notice/NewsDetailItem.jsx
1. main news/column splice 함수 slice로 수정
> fix: news/column 오류 수정

- src/styles/consul/index.scss
> feature:consul 오류 수정2

- src/styles/mng/mngConsulting.scss
- src/styles/mng/mngTrade.scss
> mng페이지 darkmode 이미지 수정

- src/pages/management/MngCredit.jsx
> mngCredit 이미지 수정

- src/pages/management/MngCredit.jsx
> mngCredit 텍스트 수정

- src/styles/mng/mngCertify.scss
> mngCredit 텍스트 width 수정

- src/styles/mng/mngValue.scss
> mngValue cicle 색상 수정

- src/pages/management/MngConsulting.jsx
- src/styles/mng/mngConsulting.scss
mngConsulting circle 텍스트 style 수정
> mngConsulting circle 텍스트 style 수정
